spring:
  application:
    name: ingsha_application_user



# before run application ,you need to modify the following configuration (nacos IP-address and create nacos-namespace ) first
nacosUrl: nacos://192.168.0.103:8848



dubbo:
  native: true
  logger: slf4j
  metadata-report:
    address: ${nacosUrl}
  application:
    name: ${spring.application.name}
    qosEnable: false
  protocol:
    name: dubbo
    port: 18102
    serialization: fastjson2
  registry:
    address: ${nacosUrl}
    group: dubbo
  consumer:
    serialization: fastjson2